# Generated by Django 5.1 on 2024-10-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_favorit', '0005_alter_favorite_product_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
