# Generated by Django 5.1 on 2024-10-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_favorit', '0006_alter_favorite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='date_added',
        ),
    ]
