# Generated by Django 5.1.2 on 2024-10-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productentry_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductEntry',
            new_name='DrugEntry',
        ),
    ]
