# Generated by Django 5.1.1 on 2024-10-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_productentry_drugentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugentry',
            old_name='age_range',
            new_name='availibility',
        ),
        migrations.RenameField(
            model_name='drugentry',
            old_name='disease',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='drugentry',
            name='stock',
        ),
    ]
