# Generated by Django 5.1.2 on 2024-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_drugentry_availibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugentry',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
