# Generated by Django 5.1.2 on 2024-10-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_drugentry_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugentry',
            old_name='img',
            new_name='image',
        ),
    ]
