# Generated by Django 5.1.2 on 2024-10-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_img_drugentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugentry',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
