# Generated by Django 5.1.2 on 2024-10-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_drugentry_image'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugentry',
            name='shops',
            field=models.ManyToManyField(related_name='ShopDrug', to='shop.shopprofile'),
        ),
    ]
