# Generated by Django 5.1.2 on 2024-10-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_drugentry_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugentry',
            name='availibility',
        ),
    ]
