# Generated by Django 5.1.2 on 2024-10-24 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('product', '0005_alter_drugentry_availibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertanyaan',
            name='user',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('answered', models.BooleanField(default=False)),
                ('drug_asked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.drugentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('drug_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.drugentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Jawaban',
        ),
        migrations.DeleteModel(
            name='Pertanyaan',
        ),
    ]
