# Generated by Django 5.1.2 on 2024-10-26 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_question_answered_answer_likes_and_more'),
        ('product', '0010_rename_img_drugentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='drug_asked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.drugentry'),
        ),
    ]
