# Generated by Django 5.1.2 on 2024-10-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_question_drug_asked'),
        ('product', '0010_rename_img_drugentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='drug_asked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.drugentry'),
        ),
    ]
