# Generated by Django 5.1.2 on 2024-10-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_question_drug_asked'),
        ('product', '0011_alter_drugentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='drug_ans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.drugentry'),
        ),
    ]
