# Generated by Django 5.1.2 on 2024-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_answer_drug_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_answer',
            field=models.IntegerField(default=0),
        ),
    ]
