# Generated by Django 5.1.2 on 2024-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_question_num_answer_question_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='num_answer',
            field=models.IntegerField(default=0),
        ),
    ]
