# Generated by Django 5.1.1 on 2024-10-26 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0002_alter_resep_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
