# Generated by Django 5.1.1 on 2024-10-26 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
