# Generated by Django 5.1.1 on 2024-10-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_created',
        ),
    ]
