# Generated by Django 5.1.2 on 2024-10-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='is_available',
        ),
    ]
