# Generated by Django 5.1.1 on 2024-10-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopentry',
            name='name',
            field=models.CharField(default='Toko', max_length=63),
        ),
    ]
